version: '3'
services:
  frontend:
    container_name: my-carrier-frontend
    build:
      context: .
      dockerfile: local.Dockerfile
    networks:
      - all_network
    volumes:
      - '.:/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  all_network:
    driver: bridge
